config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  root 'dashboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/intro/:id' => 'users#checkpoint_intro', as: 'intro'
  post '/outro/:id' => 'users#checkpoint_outro', as: 'outro'

  resources :sessions

  resources :users do
    resources :devices
  end

  resources :devices do
    resources :users
  end

  resources :au, only: :index
  get '/qr' => 'au#render_qr_code', as: 'render_qr_code'


  # get '*path' => redirect('/404')
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :users
  validates :hid, length: { is: 24 }
  validates :hid, presence: true, uniqueness: true
  accepts_nested_attributes_for :users, allow_destroy: true
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :deny

  def index
    @page_title = '- Контроллеры'
    @devices = Device.all
  end

  def new
    @page_title = '- Авторизировать контроллер'
    @device = Device.new
    @users = User.all
  end

  def create
    @device = Device.new(device_params)
    @device.users << User.find(params[:device][:user_id])
    @device.randomid = generate_api_token
    if @device.save
      redirect_to devices_path, notice: 'Контроллер авторизирован'
    else
      render 'new'
    end
  end

  def edit
    @page_title = '- Редактировать данные контроллера'
    @device = Device.find(params[:id])
    @users = @device.users.all
  end

  def update
    @device = Device.find(params[:id])
    @device.users << User.find(params[:device][:user_id])
    if @device.update(device_params)
      redirect_to devices_path
    else
      render 'new'
    end
  end

  def destroy
    if !params[:user_id].nil?
      @device = Device.find(params[:id])
      @user = @device.users.find(params[:user_id])
      if @device.users.destroy(@user)
        redirect_to edit_device_path @device.id
      end
    else
      @device = Device.find(params[:id])
      if @device.destroy
        redirect_to devices_path, notice: 'Контроллер удалён'
      end
    end
  end

  private

  def device_params
    params.require(:device).permit(:hid, :user, :user_id)
  end

end

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      .alert.alert-danger
        - @device.errors.full_messages.each do |message|
          %p
            = message
  .row
    .col-xs-12.col-md-6
      .form-group
        = f.label :hid, 'HID контроллера'
        = f.text_field :hid, class: 'form-control'
    .col-xs-12.col-md-6
      .form-group
        = f.label :user_id, 'Привязать к пользователю'
        = f.select(:user_id, User.all.collect { |u| [u.name, u.id] }, {}, class: 'form-control')






  .form-group
    = f.submit 'Подтвердить изменения', class: 'btn btn-primary'

app/views/devices/edit.html.haml
.row
  .panel.panel-default
    .panel-heading
      Редактировать данные контроллера
    .panel-body
      = render 'form'
  .panel.panel-default
    .panel-heading
      Авторизированные пользователи контроллера
    %table.table
      %thead
        %tr
          %th
            Псевдоним
          %th
            ФИО
          %th
            Действия
      %tbody
        - @users.each do |user|
          %tr
            %th
              = user.name
            %th
              = user.nickname
            %th
              = link_to 'Удалить', user_device_path(user), method: :delete, data: { confirm: 'Уверены?' }, class: 'btn btn-danger'

app/views/devices/index.html.haml
.row
  .panel.panel-default
    .panel-heading
      Список контроллеров
    %table.table
      %thead
        %tr
          %th
            HID контроллера
          %th
            RandomID
          %th
            Пользователи
          %th
            Действия
      %tbody
        - @devices.each do |device|
          %tr
            %th
              = device.hid
            %th
              = device.randomid
            %th
              = collection_select(:user, :user_id, device.users.all, :name, :name, {}, class: 'form-control')
            %th
              = link_to 'Редактировать', edit_device_path(device), class: 'btn btn-default'
              = link_to 'Удалить', device_path(device), method: :delete, data: { confirm: 'Уверены?' }, class: 'btn btn-danger'

app/views/devices/new.html.haml
.row
  .panel.panel-default
    .panel-heading
      Добавить контроллер
    .panel-body
      = render 'form'