config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  root 'dashboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/intro/:id' => 'users#checkpoint_intro', as: 'intro'
  post '/outro/:id' => 'users#checkpoint_outro', as: 'outro'

  resources :sessions

  resources :users do
    resources :devices
  end

  resources :devices do
    resources :users
  end

  resources :au, only: :index
  get '/qr' => 'au#render_qr_code', as: 'render_qr_code'


  # get '*path' => redirect('/404')
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  pg_search_scope :search_users, against: :name,
                  :using => {
                      :tsearch => {:prefix => true}
                  }
  rolify
  has_secure_password
  has_many :checkpoints, dependent: :destroy
  has_and_belongs_to_many :devices
  validates :name, presence: true, uniqueness: true
  validates :nickname, presence: true
  validates :password, presence: true, if: lambda { new_record? || !password.blank? }
  validates :password, presence: true, on: create

  private

  def self.toUnixTime(timeString)
    return DateTime.parse(timeString).to_time.to_i
  end

  def self.total_hours_today(checkpoints_object)
    diff = 0
    flag = ''
    seen = DateTime.now.to_time.to_i
    checkpoints = checkpoints_object.where('DATE(created_at) = ?', Date.today)
    checkpoints.reverse_each do |checkpoint|
      if flag == 'outro'
        diff += (seen - toUnixTime(checkpoint.created_at.to_s))
      end
      flag = checkpoint.status
      seen = toUnixTime(checkpoint.created_at.to_s)
    end
    return Time.at(diff).utc.strftime('%H:%M:%S')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :deny, except: :show

  def index
    @users = User.includes(:roles).order(updated_at: :desc)
    @page_title = '- Все пользователи'
  end

  def new
    @page_title = '- Добавить пользователя'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.add_role params[:role][:role_name]
      redirect_to users_path, notice: 'Новый пользователь в сети'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def checkpoint_intro
    @user = User.find(params[:id])
    @user.online = true
    @user.save
    @checkpoint = @user.checkpoints.new
    @checkpoint.status = 'intro'
    if @checkpoint.save
      redirect_to '/', notice: "Сотрудник #{@user.nickname} вошёл на предприятие в #{@checkpoint.created_at}"
    end
  end

  def checkpoint_outro
    @user = User.find(params[:id])
    @user.online = false
    @user.save
    @checkpoint = @user.checkpoints.new
    @checkpoint.status = 'outro'
    if @checkpoint.save
      redirect_to '/', notice: "Сотрудник #{@user.nickname} вышел из предприятия в #{@checkpoint.created_at}"
    end
  end

  def show
    @user = User.find(params[:id])
    @checkpoints = @user.checkpoints.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :nickname)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      .alert.alert-danger
        - @user.errors.full_messages.each do |message|
          %p
            = message
  .form-group
    = f.label :name, 'Псевдоним'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :nickname, 'ФИО'
    = f.text_field :nickname, class: 'form-control'
  .form-group
    = f.label :password, 'Пароль'
    = f.text_field :password, class: 'form-control'
  .form-group
    = label_tag :role, 'Привилегии'
    = collection_select :role, :role_name, Role.all, :name, :name, {}, {class: 'form-control'}

  .form-group
    = f.submit 'Подтвердить изменения', class: 'btn btn-primary'

app/views/users/edit.html.haml
.row
  .panel.panel-default
    .panel-heading
      Редактировать данные жертвы
    .panel-body
      = render 'form'

app/views/users/index.html.haml
.row
  .panel.panel-default
    .panel-heading
      Пользователи
    %table.table
      %thead
        %tr
          %th
            Псевдоним
          %th
            ФИО
          %th
            Последнее действие
          %th
            Роль
          %th
            Действия
      %tbody
        - @users.each do |user|
          %tr
            %th
              = user.name
            %th
              = user.nickname
            %th
              = l(user.updated_at, format: '%a, %d %B %Y, %H:%M:%S')
            -#%th
            -#  = User.total_hours_today(user.checkpoints)
            %th
              .label.label-default
                = user.roles.first.name
            %th
              = link_to 'Редактировать', edit_user_path(user), class: 'btn btn-default'
              = link_to 'Удалить', user_path(user), method: :delete, data: { confirm: 'Уверены?' }, class: 'btn btn-danger'

app/views/users/new.html.haml
.row
  .panel.panel-default
    .panel-heading
      Добавить пользователя
    .panel-body
      = render 'form'

app/views/users/show.html.haml
%script
  var checkpoints = #{raw @checkpoints.to_json}

.panel.panel-default
  .panel-heading
    Информация о пользователе
    = current_user.name
  .panel-body
    %table.table.table-striped
      %thead
        %tr
          %th
            Полное имя
          %th
            Роль
          %th
            Отработанное время
      %tbody
        %tr
          %td
            = @user.nickname
          %td
            .label.label-default
              = @user.roles.first.name
          %td
            = Time.parse(User.total_hours_today(@user.checkpoints)).strftime('%Hч. %Mм. %Sс.')

    %canvas#mChart{width: '600', height: '200'}