config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  root 'dashboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/intro/:id' => 'users#checkpoint_intro', as: 'intro'
  post '/outro/:id' => 'users#checkpoint_outro', as: 'outro'

  resources :sessions

  resources :users do
    resources :devices
  end

  resources :devices do
    resources :users
  end

  resources :au, only: :index
  get '/qr' => 'au#render_qr_code', as: 'render_qr_code'


  # get '*path' => redirect('/404')
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @page_title = '- Главная страница'
    if current_user
      redirect_to user_path(current_user.id) if current_user.has_role? :user
    else
      redirect_to '/login'
    end
    @results = User.search_users(params[:search_input])
    @last_changed_users = User.order(updated_at: :desc).limit(5)
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_results.html.haml
- if !params[:search_input].empty?
  - flash[:notice] = "Результат поиска по запросу #{params[:search_input]}"
  %table.table

    %tr
      %th
        Псевдоним
      %th
        ФИО
      %th
        Последнее действие
      %th
        Роль
      %th
        Действия
    %tbody
      - @results.each do |user|
        %tr
          %th
            = user.name
          %th
            = user.nickname
          %th
            = l(user.updated_at, format: '%a, %d %B %Y, %H:%M:%S')
          %th
            .label.label-default
              = user.roles.first.name
          %th
            .form-group-vertical
              .btn-group-vertical
                = link_to 'Вошёл', intro_path(user), method: :post, class: 'btn btn-default', disabled: user.online
                = link_to 'Вышёл', outro_path(user), method: :post, class: 'btn btn-default', disabled: !user.online
- else
  - flash[:notice] = "Поиск не дал результатов"

app/views/dashboards/index.html.haml
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        Поиск пользователя
      .panel-body
        .form-inline
        = form_tag root_path, method: 'get',  class: 'input-group', remote: true do
          .form-group
            = text_field_tag :search_input, params[:search_input], class: 'form-control'
          %span.input-group-btn
            = submit_tag 'Найти', name: nil, class: 'btn btn-default'
        .form-group
          #render_results
            = render 'results' if params[:search_input]

  .col-md-6
    .panel.panel-default
      .panel-heading
        Сводка о последних изменениях
      .panel-body
        %table.table.table-responsive
          %tr
            %th
              Псевдоним
            %th
              ФИО
            %th
              Последнее действие
            %th
              Статус
            %th
              Отработано сегодня
            %th
              Действие
          %tbody
            - @last_changed_users.each do |user|
              %tr
                %th
                  = user.name
                %th
                  = user.nickname
                %th
                  = l(user.updated_at, format: '%a, %d %B %Y, %H:%M:%S')
                %th
                  - if user.online
                    .label.label-success
                      На месте
                  - else
                    .label.label-danger
                      Ушёл
                %th
                  = User.total_hours_today(user.checkpoints)
                %th
                  .form-group-vertical
                    .btn-group-vertical
                      = link_to 'Вошёл', intro_path(user), method: :post, class: 'btn btn-default', disabled: user.online
                      = link_to 'Вышёл', outro_path(user), method: :post, class: 'btn btn-default', disabled: !user.online

app/views/dashboards/index.js.erb
$('#render_results').html('<%= escape_javascript(render(partial: "results")) %>');