config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  root 'dashboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/intro/:id' => 'users#checkpoint_intro', as: 'intro'
  post '/outro/:id' => 'users#checkpoint_outro', as: 'outro'

  resources :sessions

  resources :users do
    resources :devices
  end

  resources :devices do
    resources :users
  end

  resources :au, only: :index
  get '/qr' => 'au#render_qr_code', as: 'render_qr_code'


  # get '*path' => redirect('/404')
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    %title СКУД "Время" #{@page_title}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body#main-content
    %nav.navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{data: {toggle: 'collapse', target: '#bs-menu'}, 'aria-expanded' => 'false'}
            %span.sr-only
              Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: (root_url)}
            СКУД "Время" - сохрани дорогое
        .collapse.navbar-collapse#bs-menu
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: 'true', expanded: 'false'}}
                Пользователи
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Все', users_path
                %li
                  = link_to 'Добавить пользователя', new_user_path
            %li.dropdown
              %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}, role: 'button', aria: {haspopup: 'true', expanded: 'false'}}
                Устройства
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Все', devices_path
                %li
                  = link_to 'Новое устройство', new_device_path

            %li
              = link_to 'Отобразить QR-код (отладка)', render_qr_code_url
          %ul.nav.navbar-nav.navbar-right
            %li.active
              -#%a{href: '#'}
              -#  = current_user.name
              = link_to current_user.nickname, user_path(current_user.id)
            %li
              = link_to 'Выход', logout_url


    - flash.each do |name, message|
    - alert = 'alert alert-info'
    - alert = 'alert alert-danger' if name == 'alert'
      = content_tag :div, message, class: "#{alert}", id: 'flash'
    .container
      %ol.breadcrumb
        %li
          = link_to 'Главная', root_path
        - unless current_page? root_url
          %li
            = @page_title.tr('-', '') if @page_title
      = yield
    -#= console

app/views/layouts/login.html.haml
!!!
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Служба "Время" - авторизация
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |name, message|
    - alert = 'alert alert-info'
    - alert = 'alert alert-danger' if name == 'alert'
      = content_tag :div, message, class: "#{alert}", id: 'flash'
    = yield